### ISSUE TITLE
Add release docs and automation

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/tmpauthenticator#27]
### Todo

- [x] Add RELEASE.md like jupyterhub/jupyterhub
- [x] Add .github/workflows/release.yaml with automation to push to PyPI
- [ ] Prepare credentials in a GitHub Actions secret
  - [ ] Invite jupyterhub-bot as a maintainer on PyPI ([from here](https://pypi.org/manage/project/jupyterhub-tmpauthenticator/collaboration/))
  - [ ] create a PyPI deployment token from the bot for this repo specifically
